### ISSUE TITLE
Noisy OSX Travis output

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#762]
For example:
https://travis-ci.org/boostorg/beast/jobs/269682823

```
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

**Comment by vinniefalco** [comment]
Looks like this is no longer an issue: https://travis-ci.org/vinniefalco/beast/jobs/370801741
